apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: discounts-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: discounts-back
    spec:
      containers:
      - name: discounts-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: discounts-back
spec:
  ports:
  - port: 6379
  selector:
    app: discounts-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: discounts-front
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: discounts-front
    spec:
      containers:
      - name: discounts
        image: smarthotel220/discounts:latest
        imagePullPolicy: Always
        env:
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: ApplicationInsights__InstrumentationKey         
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: PATH_BASE
          value: /
        - name: profilesvc
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Discounts_profilesvc  
        ports:
        - containerPort: 80      
---
apiVersion: v1
kind: Service
metadata:
  name: discounts-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: discounts-front