apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bookings-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bookings-back
    spec:
      containers:
      - name: bookings-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: bookings-back
spec:
  ports:
  - port: 6379
  selector:
    app: bookings-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bookings-front
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: bookings-front
    spec:
      containers:
      - name: bookings-front
        image: smarthotel220/bookings:latest
        imagePullPolicy: Always
        env:
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: ApplicationInsights__InstrumentationKey                    
        - name: ASPNETCORE_ENVIRONMENT
          value: Development        
        - name: PATH_BASE
          value: /
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Bookings_ConnectionStrings__DefaultConnection
        - name: b2c__Tenant
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Bookings_b2c__Tenant             
        - name: b2c__ClientId
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Bookings_b2c__ClientId
        - name: b2c__Audiences
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Bookings_b2c__Audiences
        - name: b2c__Policy
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Bookings_b2c__Policy
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bookings-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: bookings-front