apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: configuration-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: configuration-back
    spec:
      containers:
      - name: configuration-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: configuration-back
spec:
  ports:
  - port: 6379
  selector:
    app: configuration-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: configuration-front
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: configuration-front
    spec:
      containers:
      - name: configuration-front
        image: smarthotel220/configuration:latest
        imagePullPolicy: Always
        env:
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: ApplicationInsights__InstrumentationKey             
        - name: PATH_BASE
          value: /
        - name: ASPNET_CONFIGURATION
          value: Development                
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: configuration-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: configuration-front