apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hotels-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hotels-back
    spec:
      containers:
      - name: hotels-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: hotels-back
spec:
  ports:
  - port: 6379
  selector:
    app: hotels-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hotels-front
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: hotels-front
    spec:
      containers:
      - name: hotels-front
        image: smarthotel220/hotels:latest
        imagePullPolicy: Always
        env:
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: ApplicationInsights__InstrumentationKey              
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: PATH_BASE
          value: /
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Hotels_ConnectionStrings__DefaultConnection
        - name: b2c__Tenant
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Hotels_b2c__Tenant             
        - name: b2c__ClientId
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Hotels_b2c__ClientId
        - name: b2c__Audiences
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Hotels_b2c__Audiences
        - name: b2c__Policy
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Hotels_b2c__Policy    
        - name: currency__Badge
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Hotels_currency__Badge     
        - name: currency__BaseConversion
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Hotels_currency__BaseConversion             
        - name: discountsvc
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Hotels_discountsvc                  
        ports:
        - containerPort: 80   
---
apiVersion: v1
kind: Service
metadata:
  name: hotels-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hotels-front