apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: profiles-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: profiles-back
    spec:
      containers:
      - name: profiles-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: profiles-back
spec:
  ports:
  - port: 6379
  selector:
    app: profiles-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: profiles-front
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: profiles-front
    spec:
      containers:
      - name: profiles
        image: smarthotel220/profiles:latest
        imagePullPolicy: Always
        env:
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: ApplicationInsights__InstrumentationKey       
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: PATH_BASE
          value: /
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Profiles_ConnectionStrings__DefaultConnection          
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: profiles-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: profiles-front