apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reviews-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews-back
    spec:
      containers:
      - name: reviews-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-back
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: reviews-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reviews-front
spec:
  template:
    metadata:
      labels:
        app: reviews-front
    spec:
      containers:
      - name: reviews-front
        image: smarthotel220/reviews:latest
        imagePullPolicy: Always
        env:
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: ApplicationInsights__InstrumentationKey                  
        - name: PORT
          value: "80"
        - name: ASPNET_CONFIGURATION
          value: Development          
        - name: PATH_BASE
          value: /       
        - name: sql_server_url
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Reviews_sql_server_url
        - name: sql_user_name
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Reviews_sql_user_name
        - name: sql_user_password
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Reviews_sql_user_password
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: reviews-front