apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # https://acme-staging.api.letsencrypt.org/directory
    # https://acme-staging-v02.api.letsencrypt.org/directory
    # https://acme-v01.api.letsencrypt.org/directory
    email: prosto100vip@mail.ru
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}